baseURL = '/'
languageCode = 'cs-cz'
title = 'Än'
theme = 'ananke'
canonifyURLs = true
DefaultContentLanguage = 'cs'
SectionPagesMenu = 'main'
[params]
  favicon = 'favicon.ico'
  body_classes = 'avenir bg-near-white'
